name: Full-scale-scrapper

on:
  workflow_dispatch:

jobs:
  fetch_trends:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        start: [1, 81, 161, 241, 321] # Adjust these values to cover all your indices

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - run: |
          python3 --version
          which python3
          python3 -m venv venv
          source venv/bin/activate
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          END_INDEX=$(( ${{ matrix.start }} + 79 ))
          python fetch_trends.py
        env:
          START_INDEX: ${{ matrix.start }}
          CSV_FILE_PATH: product-list/apparel_and_clothes.csv
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: combined-trends-data-${{ matrix.start }}-to-${{ matrix.start }}+79
          path: data/combined_trends_data_${{ matrix.start }}_to_${{ matrix.start }}+79.csv

  combine_data:
    runs-on: ubuntu-latest
    needs: fetch_trends
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@v3
        with:
          name: combined-trends-data-*

      - run: |
          python combine_data.py

      - uses: actions/upload-artifact@v3
        with:
          name: combined-trends-data-final
          path: data/combined_trends_data_final.csv
